language: generic 
sudo: required
services:
  - docker

  before_install:
  - docker build -t dandresbr/docker-react -f Dockerfile.dev . 

  script:
    - docker run -e CI=true dandresbr/docker-react npm run test